In [32]:
import os
os.chdir(r'C:\Users\Klsingh\Desktop\capstone project final')

In [33]:
import pandas as pd
import numpy as np
import sys
!conda install --yes --prefix {sys.prefix} numpy

Solving environment: ...working... done

# All requested packages already installed.



In [34]:
neighborhoods = os.listdir()
for x in neighborhoods:
    types_rest = os.listdir(x)
    for rest in types_rest:
        if('meta' not in rest.lower()):
            df = pd.read_csv(r'' + x + '\\' + rest, encoding = 'ISO-8859-1', engine = 'python')
            if(df.shape[1]!=15):
                print(rest)

zomato_res.csv


In [35]:
# Joining all the dataset since the dataset for each neighborhood and each category was scraped separately
listed_in = {'buffet': 'buffet_restaurants',
             'cafe': 'cafe_restaurants',
             'delivery': 'delivery_restaurants',
             'desserts': 'desserts&bakes',
             'dine': 'dineout_restaurants',
             'nightlife': 'drinks&nightlife',
             'pubs': 'pubs&bars'}
column_names = ['Cost_for_two', 'Cuisines', 'Features','Home_Delivery', 'Operational_hours', 'Restaurant_Location', 'Restaurant_Name', 'Restaurant_Type', 'View_Menu', 'Rating', 'Votes',
                              'Rating_Category', 'Operational_after_Midnight', 'Cuisine_count', 'Competitors_in_Location','Score'] 

# instantiate the dataframe
main_frame = pd.DataFrame(columns=column_names)
main_frame

Empty DataFrame
Columns: [Cost_for_two, Cuisines, Features, Home_Delivery, Operational_hours, Restaurant_Location, Restaurant_Name, Restaurant_Type, View_Menu, Rating, Votes, Rating_Category, Operational_after_Midnight, Cuisine_count, Competitors_in_Location, Score]
Index: []

In [36]:
neighborhoods = os.listdir()
for x in neighborhoods:
    types_rest = os.listdir(x)
    for rest in types_rest:
        if('meta' not in rest.lower()):
            df = pd.read_csv(r'' + x + '\\' + rest, encoding = 'ISO-8859-1', engine = 'python')
            for key, value in listed_in.items():
                if key in rest:
                    df['Listed_in(type)'] = listed_in[key]
                    df['Listed_in(city)'] = x
                    # print(listed_in[key], rest, x)
                    
            #concat dataframes
            main_frame = pd.concat([main_frame, df], ignore_index=True)

In [37]:
# Lets check the total number of restaurants in Mumbai
main_frame.shape

(6526, 16)

In [38]:
main_frame.head()

Cost_for_two                                       Cuisines  \
0         1500    Finger Food, Continental, European, Italian   
1          800                                          Pizza   
2         2500                                        Seafood   
3         1800                       Finger Food, Continental   
4          450  North Indian, Street Food, Fast Food, Chinese   

                                            Features Home_Delivery  \
0  Food Hygiene Rated Restaurants In Mumbai, Best...         False   
1                    Value For Money, Best of Mumbai         False   
2                      Super Seafood, Best of Mumbai         False   
3  Where's The Party?, Best of Mumbai, Food Hygie...         False   
4                                                NaN          True   

                                   Operational_hours    Restaurant_Location  \
0                           12noon – 1am (Mon-Sun)  Kamala Mills Compound   
1                         11am – 12:30AM (Mon-Sun)             Malad West   
2  Closed (Mon),12noon – 3pm, 7pm – 12midnigh...            Bandra West   
3                           12noon – 1am (Mon-Sun)            Lower Parel   
4          12noon – 4pm, 7pm – 11:45pm (Mon-Sun)                  Vashi   

      Restaurant_Name       Restaurant_Type View_Menu  Rating Votes  \
0  Lord of the Drinks  Lounge,Casual Dining      True     4.9  1326   
1        Joey's Pizza           Quick Bites      True     4.6  5974   
2             Bastian     Casual Dining,Bar      True     4.5  1438   
3             Tamasha            Lounge,Bar      True     4.9  3275   
4    Bhagat Tarachand         Casual Dining      True     4.1  1422   

  Rating_Category Operational_after_Midnight Cuisine_count  \
0       Excellent                       True             4   
1       Excellent                       True             1   
2       Excellent                      False             1   
3       Excellent                       True             2   
4       Very Good                      False             4   

   Competitors_in_Location      Score  
0                     19.0  48.000806  
1                    209.0  71.950295  
2                    241.0  43.160370  
3                    125.0  59.778427  
4                    116.0  37.546442

In [39]:
# We can say that the Cost_for_two of each restaurant in the dataset is our primary key
# So dropping all the data that are duplicate based on Cost_for_two column
main_frame = main_frame.drop_duplicates('Cost_for_two')

In [40]:
main_frame.shape

(75, 16)

## Cleaning the data column wise

### Lets one by one check for each column, if there is any noise in the data and clean parallely if any

#### Cost_for_two column

In [41]:
main_frame['Cost_for_two'].isnull().sum()

0

#### Cuisines column

In [42]:
main_frame['Cuisines'].isnull().sum()

0

#### Features column

In [43]:
print("NULL values : ",main_frame['Features'].isnull().sum())
print("Blank : ", (main_frame['Features']=="").sum())

NULL values :  31
Blank :  0


##### There are 31 NULL values, lets drop them

In [44]:
main_frame['Features'].replace(np.nan, '', regex=True, inplace=True)
print("NULL values : ",main_frame['Features'].isnull().sum())

NULL values :  0


#### Home_Delivery column

In [45]:
main_frame['Home_Delivery'].unique()

array([False, True], dtype=object)

#### Operational_hours column

In [46]:
print("NULL values : ",main_frame['Operational_hours'].isnull().sum())
print("Blank : ", (main_frame['Operational_hours']=="").sum())

NULL values :  0
Blank :  0


#### Restaurant_Location column

In [47]:
print("NULL values : ",main_frame['Restaurant_Location'].isnull().sum())
print("Blank : ", (main_frame['Restaurant_Location']=="").sum())

NULL values :  0
Blank :  0


In [48]:
main_frame['Restaurant_Location'].unique()

array(['Kamala Mills Compound', 'Malad West', 'Bandra West',
       'Lower Parel', 'Vashi', 'Bandra Kurla Complex', 'Juhu',
       'Cuffe Parade', 'Andheri West', 'Mahakali', 'Dadar East', 'Khar',
       'Marol', 'Kandivali West', 'Sion', 'Worli', 'Chowpatty',
       'Goregaon West', 'Borivali West', 'Powai', 'Charni Road',
       'Sakinaka', 'Matunga East', 'Colaba', 'Ghatkopar West',
       'Mahalaxmi', 'Vile Parle East', 'Grant Road', 'Vikhroli',
       'Santacruz East', 'Virar', 'Dombivali East', 'Thane West',
       'Kalyan', 'Mulund East'], dtype=object)

#### Restaurant_Name column

In [49]:
print("NULL values : ",main_frame['Restaurant_Name'].isnull().sum())
print("Blank : ", (main_frame['Restaurant_Name']=="").sum())

NULL values :  0
Blank :  0


#### Restaurant_Type column

In [50]:
print("NULL values : ",main_frame['Restaurant_Type'].isnull().sum())
print("Blank : ", (main_frame['Restaurant_Type']=="").sum())

NULL values :  3
Blank :  0


###### There are 3 NULL values, lets drop them

In [51]:
main_frame['Restaurant_Type'].replace(np.nan, '', regex=True, inplace=True)
print("NULL values : ",main_frame['Restaurant_Type'].isnull().sum())

NULL values :  0


In [52]:
main_frame[main_frame['Restaurant_Type'].isnull()].head()

Empty DataFrame
Columns: [Cost_for_two, Cuisines, Features, Home_Delivery, Operational_hours, Restaurant_Location, Restaurant_Name, Restaurant_Type, View_Menu, Rating, Votes, Rating_Category, Operational_after_Midnight, Cuisine_count, Competitors_in_Location, Score]
Index: []

In [61]:
main_frame['Restaurant_Type'].unique()

array(['Lounge,Casual Dining', 'Quick Bites', 'Casual Dining,Bar',
       'Lounge,Bar', 'Casual Dining', 'Fine Dining', 'Café', '',
       'Bar,Casual Dining', 'Bar,Lounge', 'Bar', 'Club', 'Dessert Parlor',
       'Lounge', 'Quick Bites,Dessert Parlor', 'Pub,Casual Dining',
       'Casual Dining,Pub', 'Dhaba', 'Bakery', 'Kiosk'], dtype=object)

#### View_Menu column

In [62]:
main_frame['View_Menu'].unique()

array([True], dtype=object)

#### Rating column

In [63]:
main_frame['Rating'].unique()

array([4.9, 4.6, 4.5, 4.1, 4.8, 4.7, 4.4, 3.9, 4. , 4.2, 3.8, 4.3, 3.7,
       3.5, 3.6, 3.2, 3.4, 3.3])

In [64]:
print("NULL values : ",main_frame['Rating'].isnull().sum())
print("Blank : ", (main_frame['Rating']=="").sum())

NULL values :  0
Blank :  0


C:\Users\Klsingh\Anaconda3\lib\site-packages\pandas\core\ops\array_ops.py:253: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  res_values = method(rvalues)


#### Votes column

In [65]:
main_frame['Votes'].dtype

dtype('O')

In [66]:
main_frame['Votes'].isnull().sum()

0

In [67]:
main_frame[main_frame['Votes'].isnull()]

Empty DataFrame
Columns: [Cost_for_two, Cuisines, Features, Home_Delivery, Operational_hours, Restaurant_Location, Restaurant_Name, Restaurant_Type, View_Menu, Rating, Votes, Rating_Category, Operational_after_Midnight, Cuisine_count, Competitors_in_Location, Score]
Index: []

#### Rating_Category column

In [68]:
main_frame['Rating_Category'].unique()

array(['Excellent', 'Very Good', 'Good', 'Average'], dtype=object)

#### Operational_after_Midnight column

In [69]:
main_frame['Operational_after_Midnight'].unique()

array([True, False], dtype=object)

#### Cuisine_count column

In [70]:
main_frame['Cuisine_count'].isnull().sum()

0

#### Competitors_in_Location column

In [71]:
main_frame['Competitors_in_Location'].isnull().sum()

0

#### Score column

In [72]:
main_frame['Score'].isnull().sum()

0

In [73]:
# Verifying data types for each column
main_frame.dtypes

Cost_for_two                   object
Cuisines                       object
Features                       object
Home_Delivery                  object
Operational_hours              object
Restaurant_Location            object
Restaurant_Name                object
Restaurant_Type                object
View_Menu                      object
Rating                        float64
Votes                          object
Rating_Category                object
Operational_after_Midnight     object
Cuisine_count                  object
Competitors_in_Location       float64
Score                         float64
dtype: object

#### Converting Votes column from object to integer

In [74]:
main_frame['Votes'] = main_frame['Votes'].fillna(0)
main_frame['Votes'] = main_frame['Votes'].astype(int)

In [75]:
main_frame.dtypes

Cost_for_two                   object
Cuisines                       object
Features                       object
Home_Delivery                  object
Operational_hours              object
Restaurant_Location            object
Restaurant_Name                object
Restaurant_Type                object
View_Menu                      object
Rating                        float64
Votes                           int32
Rating_Category                object
Operational_after_Midnight     object
Cuisine_count                  object
Competitors_in_Location       float64
Score                         float64
dtype: object

In [77]:
main_frame.head()

Cost_for_two                                       Cuisines  \
0         1500    Finger Food, Continental, European, Italian   
1          800                                          Pizza   
2         2500                                        Seafood   
3         1800                       Finger Food, Continental   
4          450  North Indian, Street Food, Fast Food, Chinese   

                                            Features Home_Delivery  \
0  Food Hygiene Rated Restaurants In Mumbai, Best...         False   
1                    Value For Money, Best of Mumbai         False   
2                      Super Seafood, Best of Mumbai         False   
3  Where's The Party?, Best of Mumbai, Food Hygie...         False   
4                                                             True   

                                   Operational_hours    Restaurant_Location  \
0                           12noon – 1am (Mon-Sun)  Kamala Mills Compound   
1                         11am – 12:30AM (Mon-Sun)             Malad West   
2  Closed (Mon),12noon – 3pm, 7pm – 12midnigh...            Bandra West   
3                           12noon – 1am (Mon-Sun)            Lower Parel   
4          12noon – 4pm, 7pm – 11:45pm (Mon-Sun)                  Vashi   

      Restaurant_Name       Restaurant_Type View_Menu  Rating  Votes  \
0  Lord of the Drinks  Lounge,Casual Dining      True     4.9   1326   
1        Joey's Pizza           Quick Bites      True     4.6   5974   
2             Bastian     Casual Dining,Bar      True     4.5   1438   
3             Tamasha            Lounge,Bar      True     4.9   3275   
4    Bhagat Tarachand         Casual Dining      True     4.1   1422   

  Rating_Category Operational_after_Midnight Cuisine_count  \
0       Excellent                       True             4   
1       Excellent                       True             1   
2       Excellent                      False             1   
3       Excellent                       True             2   
4       Very Good                      False             4   

   Competitors_in_Location      Score  
0                     19.0  48.000806  
1                    209.0  71.950295  
2                    241.0  43.160370  
3                    125.0  59.778427  
4                    116.0  37.546442